### ISSUE TITLE
Getting an error on running the npm test

### ISSUE THREAD

**Issue by abhijeet1810** [cuzzo/grunt-requirejs-mocha-chai-sinon-example#6]
Hi,

I am getting following warning and the test execution stops. Can you please guide me how to fix this?
Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

**Comment by cuzzo** [comment]
Hey @abhijeet1810,

What operating system are you using and which version of PhantomJS do you have installed?

Did you have any problems running `npm install`?

Thanks,

**Comment by abhijeet1810** [comment]
Hi,

Thanks for your prompt response. :) 
This issue got resolved. The bower-components were not getting installed and hence mocha, chai, sinon were not available. 
When I use a similar approach in my project, on running the npm test from command line, I get an error which says just "uncaught" in before all/before each hook. Do you have any idea why this could be happening?

Thanks
Abhijeet

**Comment by abhijeet1810** [comment]
Hi Brian,

I figured out that running the test cases fails for me if my source code has some es6 features. For example my function declaration in one of the files is as follows:
function test(flag=false){}

The test case fails with parse error exception. Parameter like flag=false is es6 feature.
As per my understanding this happens because phantom.js points to es5 and not es6. Is there a way that I can say phantom.js to use es6?

The same test cases run fine through html page.
Any pointer will be really helpful.

Thanks 
Abhijeet

**Comment by cuzzo** [comment]
Hey @abhijeet1810,

It seems PhantomJS won't support es6 fully until [version 2.5](https://github.com/ariya/phantomjs/milestone/16) is released. So until then, I think you'd have to use babel to translate your code from es6 to es5 before you run it through tests.

Cheers,

**Comment by abhijeet1810** [comment]
Thanks you. :)
